/* GALPI 3-3: independent, memory-only learning module. No economic scores. */
(()=>{'use strict';
const host=()=>document.querySelector('#content');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const actors=['정부','기업','노동자','소비자'];
const icons={government:'<path d="M4 9h16L12 3 4 9zm2 3v7m4-7v7m4-7v7m4-7v7M3 21h18"/>',company:'<path d="M3 21V10l6 3V8l6 4V3h5v18H3zm3-5h1m4 0h1m4 0h1"/>',worker:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-3a8 8 0 0116 0v3M8 16v5m8-5v5"/>',consumer:'<path d="M5 8h14l2 13H3L5 8zm3 0V6a4 4 0 018 0v2"/>',shirt:'<path d="M8 3l4 2 4-2 6 5-4 4-2-2v11H8V10l-2 2-4-4 6-5z"/>',water:'<path d="M10 2h4v4l3 3v12H7V9l3-3V2zm-3 11h10m-7-7h4"/>',message:'<path d="M3 3h18v14H8l-5 4V3zm4 5h10M7 12h7"/>',leaf:'<path d="M20 3C7 2 2 8 5 15c4 8 14 3 15-12zM4 21L16 9"/>',truck:'<path d="M2 5h12v12H2V5zm12 5h5l3 4v3h-8"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>'};
function icon(key){return `<svg class="rr-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[key]||icons.leaf}</svg>`;}
const companies=[
 {id:'maintain',name:'기존 생산 유지',desc:'법적 기준을 지키며 기존 비용 구조를 유지합니다.',tag:'경쟁력 유지',effect:'추가 투자 부담은 작지만, 기존 공정의 환경 영향을 더 줄일 기회는 제한될 수 있습니다.',link:['기업','소비자']},
 {id:'safety',name:'안전 설비에 투자',desc:'법적 기준을 넘어서는 안전 설비와 교육에 투자합니다.',tag:'위험 감소 가능성',effect:'작업 위험을 줄일 가능성이 있습니다. 기업은 설비 비용과 교육·정비 계획을 함께 고려해야 합니다.',link:['기업','노동자']},
 {id:'clean',name:'오염 저감 기술 도입',desc:'공정에서 나오는 오염을 줄이는 기술을 도입합니다.',tag:'환경 개선 가능성',effect:'오염 배출을 줄일 가능성이 있습니다. 초기 투자와 유지 비용이 발생하며, 실제 효과는 공정과 관리에 달려 있습니다.',link:['기업','정부']},
 {id:'innovation',name:'새로운 소재 개발',desc:'재활용이 쉬운 소재와 생산 기술을 연구합니다.',tag:'불확실성·혁신',effect:'기술 개발이 성공하면 장기 경쟁력과 환경 개선을 함께 기대할 수 있습니다. 개발 실패와 성능 검증의 불확실성도 있습니다.',link:['기업','소비자']}
];
const policies=[{id:'rules',name:'환경 기준 강화',desc:'배출 기준과 준수 여부를 점검합니다.'},{id:'incentive',name:'저감 투자에 유인 제공',desc:'환경 개선 투자 조건에 맞춰 지원합니다.'},{id:'disclosure',name:'생산 정보 공개 기준',desc:'확인 가능한 노동·환경 정보를 요구합니다.'}];
const demands=[{id:'price',name:'가격을 먼저 비교',desc:'예산과 품질을 함께 고려합니다.'},{id:'trace',name:'생산 과정을 확인',desc:'자료의 출처와 검증 여부를 살펴봅니다.'},{id:'ethics',name:'노동·환경을 함께 고려',desc:'구매 기준에 노동 조건과 환경 정보를 포함합니다.'}];
const model={mode:'simulation',teacher:false,step:0,unlocked:0,product:null,pipeline:0,visited:[],company:null,policy:null,demand:null,actor:'기업',caseId:'uniform',cases:{},reflectSource:'simulation',reflectActor:'소비자',finalProduct:null,reason:'',conceptAnswer:null};
const stages=['첫 선택','만들어지는 과정','기업의 결정','함께 대응하기','선택의 파장'];
const supply=['원료','생산','운송','판매','소비'];
function derive(s){
 const c=companies.find(x=>x.id===s.company),p=policies.find(x=>x.id===s.policy),d=demands.find(x=>x.id===s.demand);
 if(!c)return {links:[],effects:[],summary:'기업의 결정을 선택해 연결 관계를 살펴보세요.'};
 const links=[c.link],effects=[{actor:'기업',label:c.tag,text:c.effect}];
 if(c.id==='safety')effects.push({actor:'노동자',label:'작업 환경',text:'설비뿐 아니라 교육과 현장 의견 반영이 있어야 안전 개선으로 이어질 수 있습니다.'});
 else effects.push({actor:'노동자',label:'현장 참여',text:c.id==='innovation'?'새 소재·공정에 필요한 교육과 작업 조건을 노동자와 협의해야 합니다.':'모든 생산 방식에서 법적 안전 기준과 노동자의 권리를 보장해야 합니다.'});
 if(p){links.push(['정부','기업']);let text;
 if(p.id==='rules')text=c.id==='clean'?'도입한 저감 기술이 새 기준을 충족하는지 확인합니다. 규제 목적과 점검·준수 비용을 함께 살펴봅니다.':c.id==='innovation'?'새 소재의 개발만으로 배출 기준을 충족한다고 볼 수 없습니다. 기존 공정의 준수 계획도 필요합니다.':'선택한 기업 전략과 별개로 배출 기준을 충족해야 합니다. 공정 점검과 추가 대응 비용이 발생할 수 있습니다.';
 if(p.id==='incentive')text=c.id==='clean'?'저감 설비가 지원 조건에 맞는다면 초기 투자 부담을 덜 수 있습니다. 재정 비용과 성과 확인이 필요합니다.':c.id==='innovation'?'연구 지원과 실제 저감 투자 지원은 다를 수 있습니다. 개발 단계·검증 기준에 맞는 지원인지 확인해야 합니다.':'안전 투자나 기존 공정 유지가 환경 지원 대상이라는 보장은 없습니다. 정책 목적에 맞는 추가 계획이 필요합니다.';
 if(p.id==='disclosure')text=c.id==='safety'?'안전 설비·교육 기록을 공개하면 노동 조건을 비교할 근거가 늘어납니다. 기록을 확인하는 절차도 필요합니다.':c.id==='clean'?'저감 기술 도입 사실뿐 아니라 배출 변화 자료를 공개해야 소비자가 효과를 판단할 수 있습니다.':'소재·공정의 출처와 검증 자료를 공개해야 합니다. 광고 문구만으로 책임 있는 생산을 확인할 수 없습니다.';
 effects.push({actor:'정부',label:p.id==='incentive'?'재정·성과 조건':'목적·집행 비용',text});}
 if(d){links.push(['소비자','기업']);let text;
 if(d.id==='price')text=`기업의 ${c.name} 결정이 가격·품질에 어떻게 반영되는지 확인합니다. 낮거나 높은 가격만으로 윤리성을 판단할 수 없습니다.`;
 if(d.id==='trace')text=p?.id==='disclosure'?'공개 기준으로 늘어난 생산 정보를 비교할 수 있습니다. 누가 확인한 자료인지 살펴야 신뢰를 판단할 수 있습니다.':'생산 정보를 요청할 수 있지만 공개된 자료가 충분하지 않을 수 있습니다. 확인되지 않은 부분은 판단을 유보할 수 있습니다.';
 if(d.id==='ethics')text=c.id==='safety'?'안전 설비 투자는 구매 판단의 한 근거입니다. 임금·노동시간·환경 영향 자료까지 함께 확인해야 합니다.':c.id==='clean'?'환경 개선 가능성을 고려하되 노동 조건과 실제 저감 자료도 확인합니다. 한 지표만으로 전체 윤리성을 판정하지 않습니다.':c.id==='innovation'?'개발 계획과 검증된 성과를 구분합니다. 혁신에 대한 기대가 현재의 노동·환경 책임을 대신하지 않습니다.':'가격과 품질뿐 아니라 현재의 노동 조건·환경 정보가 충분한지 확인하고 추가 개선을 요구할 수 있습니다.';
 effects.push({actor:'소비자',label:'판단 근거',text});}
 return {links,effects,summary:`기업의 ${c.name}${p?` → 정부의 ${p.name}`:''}${d?` → 소비자의 ${d.name}`:''}`};
}
const caseData={
 uniform:{title:'교복 가격 담합',subtitle:'여러 업체가 참여하면 경쟁일까요?',kind:'실제 사건 기반 · 입찰 화면은 가상 재구성',icon:'shirt',situation:'학교의 교복 공동구매에 세 업체가 참여했습니다. 서로 다른 견적서를 제출했다는 정보만 알고 있습니다.',choices:['공정한 경쟁으로 보인다','경쟁이 제한되었을 수 있다','추가 자료가 필요하다'],evidence:'공정위는 구미지역 6개 교복 판매사업자가 학교주관 공동구매 입찰에서 낙찰 예정자를 미리 정하고 들러리 투찰에 참여한 담합을 제재했습니다. 여러 업체의 참여만으로 독립적인 경쟁을 보장할 수 없습니다.',facts:['처음: 업체별 견적서 제출','공개된 정보: 낙찰 예정자 사전 합의','연결: 경쟁 제한 → 소비자의 선택 조건에 영향'],perspectives:{정부:'사전 합의를 조사하고 공정한 입찰을 회복할 필요가 있습니다. 조사·집행에는 자료와 비용이 필요합니다.',기업:'독립적으로 가격과 품질을 경쟁해야 합니다. 낙찰자를 사전에 정하는 방식은 정당한 경쟁 전략이 아닙니다.',노동자:'기업 간 경쟁 방식은 주문과 업무에도 영향을 줄 수 있습니다. 담합이 노동자에게 유리하다고 단정할 수 없습니다.',소비자:'경쟁이 제한되면 가격·품질을 비교해 고를 기회가 줄어들 수 있습니다. 이 자료만으로 개별 피해액을 계산할 수는 없습니다.'},concept:'공정 경쟁 · 불공정 거래 · 소비자 권익 · 정부의 역할',connection:'정부의 조사는 소비자 권익 보호와 연결되고, 기업의 독립적인 경쟁은 시장이 작동하는 조건입니다.',source:'https://www.ftc.go.kr/www/selectBbsNttView.do?bordCd=3&key=12&nttSn=46169',sourceName:'공정거래위원회 · 구미지역 6개 교복판매사업자의 부당한 공동행위 제재'},
 water:{title:'무라벨 생수와 윤리적 소비',subtitle:'라벨이 없으면 충분할까요?',kind:'현실 자료 기반 · 과거 포장 방식을 포함한 가상 비교',icon:'water',situation:'같은 용량의 라벨 생수와 무라벨 생수를 비교합니다. 무라벨 제품의 광고에는 “분리배출을 더 쉽게”라고 적혀 있습니다. 재료·운송 자료는 아직 없습니다.',choices:['광고만으로 친환경성을 판단할 수 있다','무라벨은 친환경성과 무관하다','추가 자료와 배출 과정이 중요하다'],evidence:'한국환경공단은 무라벨 페트병과 포장재 재질·구조 평가, 투명 페트병의 별도 배출을 함께 안내합니다. 라벨 제거는 배출 과정의 한 요소이며, 환경 효과를 판단하려면 제품 설계와 실제 배출·재활용 조건을 함께 살펴야 합니다.',facts:['라벨 제품: 라벨 분리 → 병 배출','무라벨 제품: 라벨 분리 단계 생략 → 병 배출','공통: 내용물 비우기·배출 방식·처리 조건 확인'],perspectives:{정부:'재활용하기 쉬운 포장 설계와 분리배출 안내를 마련합니다. 표시 기준과 실제 처리 환경도 확인합니다.',기업:'포장을 개선하고 재료·재활용 관련 정보를 신뢰할 수 있게 제공합니다. 환경 성과를 과장하지 않아야 합니다.',노동자:'생산·수거·선별 현장의 작업 조건도 고려해야 합니다. 환경 지표만으로 노동 환경이 좋다고 볼 수 없습니다.',소비자:'광고보다 재료, 포장 전체, 재활용 용이성, 배출 방법을 확인합니다. 같은 가격이라도 정보의 질은 다를 수 있습니다.'},concept:'기업의 사회적 책임 · ESG 경영 · 윤리적 소비',connection:'환경(E) 정보 한 가지가 사회(S)·지배구조(G)의 모든 성과를 보장하지 않습니다. 구매와 올바른 배출은 함께 고려할 수 있습니다.',source:'https://www.keco.or.kr/group05/lay1/bbs/S300T769C775/A/20/view.do?article_seq=10812',sourceName:'한국환경공단 · 슬기로운 소비·배출생활 안내(2021)'},
 contact:{title:'퇴근 후 업무 연락',subtitle:'내일의 업무, 오늘의 휴식',kind:'현실 쟁점 기반 · 수업용 가상 상황',icon:'message',situation:'퇴근한 노동자에게 “내일 발표 자료를 오늘 밤 수정해 주세요”라는 연락이 왔습니다. 예상 작업 시간과 긴급 사유, 근무 합의는 알려져 있지 않습니다.',choices:['연락을 받으면 항상 즉시 처리해야 한다','퇴근 후 연락은 상황과 무관하게 모두 금지해야 한다','긴급성·근무 조건·휴식을 함께 확인해야 한다'],evidence:'추가 상황: 관리자는 고객 일정이 바뀌었다고 설명합니다. 노동자는 돌봄 일정이 있고, 야간 대응 담당이나 보상 기준은 합의되어 있지 않습니다. 이는 법률 위반 여부를 확정하는 사례가 아니라 연락 기준을 함께 설계하는 활동입니다.',facts:['노동자: 휴식·돌봄 일정','관리자: 변경된 고객 일정','확인할 조건: 긴급성·담당·시간 기록·보상'],perspectives:{정부:'노동시간과 보상에 관한 제도를 집행하고 실제 근로 조건을 확인합니다. 정책 논의와 현재 법적 권리는 구분해야 합니다.',기업:'긴급 연락과 다음 날 처리할 업무를 구분하고 담당·연락 시간·기록 기준을 정합니다. 법적 기준을 협의로 없앨 수는 없습니다.',노동자:'휴식과 예측 가능한 근무 조건이 중요합니다. 업무 지시, 실제 작업, 시간 기록과 보상 조건을 확인해야 합니다.',소비자:'빠른 서비스의 편익 뒤에 다른 사람의 노동과 휴식이 있습니다. 모든 요청을 즉시 처리해야 한다고 기대할 필요는 없습니다.'},concept:'노동자의 권리 · 상생하는 노사 관계 · 정부의 역할',connection:'“연결되지 않을 권리”에 관한 논의와 개별 사안의 근로시간·보상 판단은 구분합니다. 최신 고용노동부 자료는 실제 근로시간 기록과 정당한 보상의 중요성을 안내합니다.',source:'https://www.moel.go.kr/news/enews/report/enewsView.do?news_seq=19943',sourceName:'고용노동부 · 포괄임금 오남용 기획 감독(2026-09-15)',extraSource:'https://www.moel.go.kr/policy/policydata/view.do?bbs_seq=20180600324'}
};
function caseState(){return model.cases[model.caseId]||(model.cases[model.caseId]={stage:0,initial:null,final:null,revealed:false,completed:false,actor:'노동자',seen:[],reason:'',criteria:[]});}
function button(label,action,value='',selected=false,disabled=false,cls=''){return `<button type="button" class="btn ${cls} ${selected?'rr-selected':''}" data-rr="${action}" data-value="${escape(value)}" ${disabled?'disabled':''} ${['actor','stage','case','case-actor','reflect-actor','final-product','concept'].includes(action)?`aria-pressed="${!!selected}"`:''}>${label}</button>`;}
function picks(items,key,action){return `<div class="rr-choices">${items.map(x=>`<button class="rr-choice ${model[key]===x.id?'rr-selected':''}" type="button" data-rr="${action}" data-value="${x.id}" aria-pressed="${model[key]===x.id}"><strong>${x.name}</strong><span>${x.desc}</span>${x.tag?`<small>${x.tag}</small>`:''}</button>`).join('')}</div>`;}
function sectionHead(n,h,p=''){return `<div class="rr-section-head"><span class="rr-step">${n}</span><div><h2>${h}</h2>${p?`<p>${p}</p>`:''}</div></div>`;}
function network(){const out=derive(model);const coords={'정부':[25,25],'기업':[75,25],'노동자':[25,75],'소비자':[75,75]};return `<div class="rr-network"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${[['정부','기업'],['기업','노동자'],['기업','소비자'],['소비자','정부'],['노동자','소비자']].map(([a,b])=>{const on=out.links.some(x=>x.includes(a)&&x.includes(b));return `<line x1="${coords[a][0]}" y1="${coords[a][1]}" x2="${coords[b][0]}" y2="${coords[b][1]}" class="${on?'rr-link-active':''}"/>`;}).join('')}</svg>${actors.map((a,i)=>`<button type="button" data-rr="actor" data-value="${a}" aria-pressed="${model.actor===a}" class="rr-actor ${model.actor===a?'rr-selected':''}">${icon(['government','company','worker','consumer'][i])}<strong>${a}</strong><span>${out.effects.find(x=>x.actor===a)?.label||'상호 의존'}</span></button>`).join('')}</div><p class="rr-caption">주체를 누르면 영향을 확인할 수 있습니다. 강조된 선은 현재 선택과 관련된 관계입니다. 인과의 크기나 확정된 성과를 뜻하지 않습니다.</p>`;}
function impact(){const out=derive(model),shown=out.effects.filter(e=>e.actor===model.actor);return `<aside class="rr-impact" aria-live="polite"><h3>${model.actor}에게 이어지는 영향</h3>${shown.length?shown.map(e=>`<span class="pill">${e.label}</span><p>${e.text}</p>`).join(''):'<p>이 주체의 대응은 다음 선택에서 연결됩니다. 모든 주체는 다른 주체의 조건을 함께 살펴야 합니다.</p>'}<details><summary>현재 선택의 연결 모두 보기</summary>${out.effects.map(e=>`<p><b>${e.actor}</b> · ${e.text}</p>`).join('')}</details></aside>`;}
function flowInfo(){const selected=model.product==='A';const details=[['원료의 출처',selected?'A는 일반 면을 사용합니다. 물·농약 사용량 자료는 제공되지 않았다는 가정입니다.':'B는 재생 섬유 혼방을 사용한다는 가정입니다. 재생 원료의 비율·내구성·재활용성 검증 자료를 추가로 확인해야 합니다.','원료의 성질 → 공정·품질·폐기 단계에 영향'],['생산과 노동', 'A와 B 모두 법적 노동·안전 기준을 준수한다는 가정입니다. 기준 이상의 안전 개선 여지는 있으며, 가격으로 노동 조건을 추정하지 않습니다.','설비·교육 → 노동자의 작업 환경과 기업의 비용'],['운송 과정','두 제품의 배송 방식은 같다는 가정입니다. 실제 환경 영향은 거리·수단·포장에 따라 달라지며 수치는 주어지지 않았습니다.','운송 조건 → 소비자의 수령과 환경 영향'],['가격과 판매','A의 가격은 9,900원, B는 19,900원입니다. 수업용 가격이며, 비싸다는 이유로 더 윤리적인 제품이라고 판정하지 않습니다.','기업의 비용·경쟁 → 가격·품질·소비자의 예산'],['사용과 배출','오래 사용하고 수선할 수 있는지, 폐기할 때 분리·재활용할 수 있는지를 확인합니다. 소재만으로 실제 재활용 여부를 보장할 수 없습니다.','소비자의 사용·배출 → 제품 수명과 처리 과정']];const [h,p,link]=details[model.pipeline];return `<div class="rr-flow">${supply.map((x,i)=>`<button type="button" data-rr="pipeline" data-value="${i}" class="${model.pipeline===i?'rr-selected':''}" aria-pressed="${model.pipeline===i}">${icon(['leaf','company','truck','consumer','water'][i])}<span>${x}</span><small>${model.visited.includes(i)?'확인함':'살펴보기'}</small></button>`).join('')}</div><div class="rr-reveal"><h3>${h}</h3><p>${p}</p><div class="rr-chain">${link}</div></div>`;}
function simulation(){let content='';const step=model.step;
 if(step===0)content=`${sectionHead('1','티셔츠 한 장, 무엇을 고를까요?','지금 확인할 수 있는 것은 디자인·가격·배송입니다.')}<div class="rr-products">${['A','B'].map((x,i)=>`<button class="rr-product ${model.product===x?'rr-selected':''}" type="button" data-rr="product" data-value="${x}" ${model.unlocked>0?'disabled':''} aria-pressed="${model.product===x}"><div class="rr-product-art ${i?'rr-product-b':''}">${icon('shirt')}</div><div><span>제품 ${x}</span><strong>${i?'19,900':'9,900'}원</strong><small>기본 배송 · 가상 제품</small></div></button>`).join('')}</div><p class="rr-note">${model.unlocked>0?'처음 선택은 비교를 위해 그대로 기록합니다. 마지막에 지금의 선택을 다시 정할 수 있습니다. ':''}처음 선택에는 정답이 없습니다. 가격만으로 생산 과정의 윤리성을 알 수 없으며, 이후 공개되는 조건도 수업용 가정입니다.</p>`;
 if(step===1)content=`${sectionHead('2','이 티셔츠는 어디에서 왔을까요?','각 과정을 눌러 정보와 다음 단계의 연결을 확인하세요.')}<span class="pill">처음 선택 · 제품 ${model.product}</span>${flowInfo()}<p class="rr-note">${model.visited.length}/5 과정 확인 · 다섯 과정을 살펴본 뒤 기업의 입장으로 이동합니다.</p>`;
 if(step===2)content=`${sectionHead('3','이번에는 의류 회사의 경영자입니다.','모든 선택은 법적 노동·안전 기준을 준수한다는 가정입니다. 무엇에 먼저 투자할까요?')}<div class="rr-workspace"><div>${picks(companies,'company','company')}</div><div>${network()}</div>${impact()}</div>`;
 if(step===3)content=`${sectionHead('4','다른 주체는 어떻게 대응할까요?','앞서 선택한 기업 결정에 정부·소비자의 대응을 더해 보세요.')}<div class="rr-workspace"><div><h3>정부의 정책</h3>${picks(policies,'policy','policy')}<h3>소비자의 구매 기준</h3>${picks(demands,'demand','demand')}</div><div>${network()}<div class="rr-trail">${derive(model).summary}</div></div>${impact()}</div>`;
 if(step===4)content=`${sectionHead('5','한 선택은 여러 방향으로 이어집니다.','선택의 누적 결과를 살펴보세요. 환경·이윤·권리를 임의 점수로 환산하지 않습니다.')}<div class="rr-workspace rr-final"><div><h3>내가 만든 선택의 흐름</h3><ol class="rr-decisions"><li>처음 구매 · 제품 ${model.product}</li><li>${companies.find(x=>x.id===model.company)?.name}</li><li>${policies.find(x=>x.id===model.policy)?.name}</li><li>${demands.find(x=>x.id===model.demand)?.name}</li></ol><p>같은 기업 결정도 정책 조건과 소비자의 판단 기준에 따라 후속 영향이 달라집니다.</p></div><div>${network()}</div>${impact()}</div><div class="rr-question"><h3>어느 한 경제 주체의 노력만으로 충분할까요?</h3><p>기업의 기술·생산, 정부의 규칙, 노동자의 참여, 소비자의 정보 확인이 어떻게 이어지는지 생각해 보세요.</p>${button('내 판단 다시 살펴보기 →','reflect-sim','','',false,'primary')}</div>`;
 const allowed=step===0?!!model.product:step===1?model.visited.length===5:step===2?!!model.company:step===3?!!model.policy&&!!model.demand:true;
 return `<div class="rr-stage-nav" aria-label="시뮬레이션 단계">${stages.map((s,i)=>button(`${i+1}. ${s}`,'stage',i,step===i,i>model.unlocked)).join('')}</div><section class="rr-surface">${content}<div class="rr-actions">${button('이전 단계','sim-prev','',false,step===0)}${step<4?button('다음 단계 →','sim-next','',false,!allowed,'primary'):button('현실 사례 탐구 →','mode','cases',false,false,'primary')}</div></section>`;
}
const criteria=['가격·예산','공정 경쟁','노동 조건·휴식','환경·재활용','자료의 신뢰성','정책의 효과·비용'];
function criteriaControls(cs){return `<div class="rr-checks">${criteria.map(c=>`<label><input type="checkbox" data-rr-criteria="${escape(c)}" ${cs.criteria.includes(c)?'checked':''}>${c}</label>`).join('')}</div>`;}
function caseVisual(id,stage){const c=caseData[id];if(id==='uniform')return `<div class="rr-bids ${stage>=2?'rr-bids-revealed':''}"><div class="rr-bid-links">${stage>=2?'사전 합의: 낙찰 예정자 결정':'독립적인 경쟁일까요?'}</div><div class="rr-bid-row">${['업체 A','업체 B','업체 C'].map((x,i)=>`<div>${icon('shirt')}<strong>${x}</strong><span>${stage>=2?(i===0?'예정된 낙찰자':'들러리 참여'):'견적서 제출'}</span></div>`).join('')}</div><p>→ 학교 공동구매 → 학생·학부모의 선택 조건</p></div>`;
 if(id==='water')return `<div class="rr-waterflow"><div>${icon('water')}<b>라벨 제품</b><span>라벨 분리 → 병 배출</span></div><div>${icon('water')}<b>무라벨 제품</b><span>병 배출</span></div>${stage>=2?'<p>두 경로 모두 → 수거·선별 → 재활용 조건 확인<br>라벨 제거 한 가지로 제품 전체의 환경 성과를 판정하지 않습니다.</p>':''}</div>`;
 return `<div class="rr-timeline"><div><time>18:00</time><span>퇴근 · 휴식 시작</span></div><div><time>20:30</time><span>자료 수정 요청</span></div>${stage>=2?'<div><time>확인</time><span>긴급 사유 · 담당 · 작업 시간 · 보상 기준</span></div>':''}</div>`;
}
function caseChoices(c,cs,final=false){return `<div class="rr-choices">${c.choices.map((v,i)=>`<button type="button" class="rr-choice ${(final?cs.final:cs.initial)===i?'rr-selected':''}" data-rr="${final?'case-final':'case-initial'}" data-value="${i}" ${!final&&cs.revealed?'disabled':''} aria-pressed="${(final?cs.final:cs.initial)===i}">${v}</button>`).join('')}</div>`;}
function sources(c){return `<details class="rr-sources"><summary>출처와 수업용 재구성 확인</summary><p><a href="${c.source}" target="_blank" rel="noopener">${c.sourceName} ↗</a></p>${c.extraSource?`<p><a href="${c.extraSource}" target="_blank" rel="noopener">고용노동부 · 근로시간 판단 기준(2018, 과거 자료) ↗</a></p>`:''}<p>자료 확인: 2026-10-09. 실제 기관 자료와 가상 제품·대화·입찰 도식은 구분합니다. 최신 법률의 일률적인 결론이나 피해액은 제시하지 않습니다.</p></details>`;}
function caseExplore(){const c=caseData[model.caseId],cs=caseState(),stage=cs.stage;let content='';
 if(stage===0)content=`${sectionHead('1',c.subtitle,c.kind)}<p class="rr-lead">${c.situation}</p>${caseVisual(model.caseId,stage)}`;
 if(stage===1)content=`${sectionHead('2','지금 정보로 먼저 판단해 보세요.','맞고 틀림으로 평가하지 않습니다.')}<p>${c.situation}</p>${caseChoices(c,cs)}${cs.revealed?'<p class="rr-note">첫 판단은 자료 공개 전의 기록으로 유지합니다. 최종 판단에서 다시 선택할 수 있습니다.</p>':''}`;
 if(stage===2)content=`${sectionHead('3','새 자료를 확인합니다.',c.kind)}${caseVisual(model.caseId,stage)}<div class="rr-reveal"><p>${c.evidence}</p></div>${sources(c)}`;
 if(stage===3)content=`${sectionHead('4','다른 주체는 무엇을 고려할까요?','네 관점을 모두 살펴보고 다시 판단해 보세요.')}<div class="rr-perspective-tabs">${actors.map(a=>button(a,'case-actor',a,cs.actor===a)).join('')}</div><div class="rr-reveal"><h3>${cs.actor}의 관점</h3><p>${c.perspectives[cs.actor]}</p></div><p class="rr-note">살펴본 관점: ${cs.seen.join(' · ')||'아직 없음'} (${cs.seen.length}/4)</p>`;
 if(stage===4)content=`${sectionHead('5','추가 정보를 고려한 지금의 판단은?','처음과 같은 판단이어도 괜찮습니다. 근거를 넓혀 보세요.')}<p>${c.subtitle}</p>${caseChoices(c,cs,true)}<h3>판단에 사용한 근거</h3>${criteriaControls(cs)}<label class="rr-writing">내가 더 고려하게 된 점 (선택)<textarea maxlength="600" data-rr-text="case" placeholder="특정 입장에 동의하기보다, 어떤 정보가 판단에 중요했는지 적어 보세요.">${escape(cs.reason)}</textarea></label>`;
 if(stage===5)content=`${sectionHead('6','처음과 지금, 근거를 비교합니다.','의견이 바뀌었는지보다 무엇을 더 고려했는지가 중요합니다.')}<div class="rr-comparison"><div><span>처음 판단</span><h3>${c.choices[cs.initial]}</h3></div><div><span>최종 판단</span><h3>${c.choices[cs.final]}</h3></div></div><p>${cs.initial===cs.final?'판단을 유지했습니다. 추가 근거를 확인한 것도 탐구의 성과입니다.':'추가 정보를 바탕으로 판단을 다시 구성했습니다.'}</p><p><b>고려한 근거:</b> ${cs.criteria.join(' · ')||'아직 선택하지 않았습니다.'}</p>${cs.reason?`<blockquote>${escape(cs.reason)}</blockquote>`:''}<p class="rr-note">의견에 점수를 매기지는 않지만, 자료로 확인한 사실과 자신의 판단은 구분해서 살펴보세요.</p><div class="rr-concept"><h3>${c.concept}</h3><p>${c.connection}</p></div>${sources(c)}${button('다른 관점으로 이어 보기 →','reflect-case','','',false,'secondary')}`;
 const allowed=stage===1?cs.initial!==null:stage===3?cs.seen.length===4:stage===4?cs.final!==null&&cs.criteria.length>0:true;
 return `<div class="rr-case-menu" aria-label="현실 사례 선택">${Object.entries(caseData).map(([key,v])=>button(`${icon(v.icon)}${v.title}`,'case',key,model.caseId===key)).join('')}</div><section class="rr-surface"><div class="rr-case-heading"><h2>${c.title}</h2><span class="pill">${stage+1} / 6</span></div>${content}<div class="rr-actions">${button('이전 정보','case-prev','',false,stage===0)}${stage<5?button(stage===1?'추가 정보 공개 →':stage===4?'판단 비교하기 →':'다음 →','case-next','',false,!allowed,'primary'):button('다시 생각하기 →','reflect-case','',false,false,'primary')}</div></section>`;
}
function reflection(){const from=model.reflectSource,c=caseData[from],cs=c?model.cases[from]:null;const ready=c?cs?.completed:model.unlocked===4;const views=c?c.perspectives:{정부:'공정 경쟁·노동자의 권리·소비자 보호와 함께 정책의 집행 비용과 효과를 고려합니다.',기업:'생산비·이윤·품질·장기 경쟁력을 고려합니다. 혁신은 사회적 책임과 함께 추진할 수 있습니다.',노동자:'법적 권리·임금·고용 안정·안전한 작업 환경을 고려합니다. 가격 협상과 기본권 보장은 구분해야 합니다.',소비자:'예산·가격·품질·노동·환경 정보와 자료의 신뢰성을 함께 고려합니다.'};
 return `<section class="rr-surface">${sectionHead('↔','같은 상황, 다른 관점','관점을 바꾸어도 정답이나 의견 점수는 매기지 않습니다.')}<div class="rr-source-select"><label for="rr-reflect-source">돌아볼 활동</label><select id="rr-reflect-source" data-rr-select="source"><option value="simulation" ${from==='simulation'?'selected':''}>티셔츠 한 장의 선택</option>${Object.entries(caseData).map(([id,x])=>`<option value="${id}" ${from===id?'selected':''}>${x.title}</option>`).join('')}</select></div><div class="rr-central"><h3>${c?c.subtitle:'생산 조건을 바꾸면, 제품 선택도 달라질까요?'}</h3><p>${c?c.situation:'안전·환경 개선에는 비용과 검증이 필요합니다. 앞서 선택한 기업·정부·소비자의 조건을 함께 고려해 보세요.'}</p></div><div class="rr-perspective-tabs">${actors.map(a=>button(a,'reflect-actor',a,model.reflectActor===a)).join('')}</div><div class="rr-reveal"><h3>${model.reflectActor}의 관점</h3><p>${views[model.reflectActor]}</p></div>${!ready?`<div class="rr-empty"><h3>먼저 이 활동의 판단을 완성해 보세요.</h3><p>선택과 자료 확인을 마치면 처음·최종 판단을 비교할 수 있습니다.</p>${button('활동 이어하기 →','resume-source','',false,false,'primary')}</div>`:c?`<div class="rr-comparison"><div><span>처음 판단</span><h3>${c.choices[cs.initial]}</h3></div><div><span>최종 판단</span><h3>${c.choices[cs.final]}</h3></div></div><p><b>고려한 근거:</b> ${cs.criteria.join(' · ')}</p><p>${c.connection}</p>`:`<h3>생산 정보를 확인한 뒤의 제품 선택</h3><div class="rr-perspective-tabs">${['A','B','추가 정보가 필요하다'].map(x=>button(x.length===1?`제품 ${x}`:x,'final-product',x,model.finalProduct===x)).join('')}</div><label class="rr-writing">새롭게 고려한 근거 (선택)<textarea data-rr-text="simulation" maxlength="600" placeholder="기업·정부·노동자·소비자의 조건 중 어떤 점이 중요했나요?">${escape(model.reason)}</textarea></label><div class="rr-comparison"><div><span>처음 선택</span><h3>제품 ${model.product}</h3></div><div><span>지금 선택</span><h3>${model.finalProduct?(model.finalProduct.length===1?'제품 '+model.finalProduct:model.finalProduct):'아직 선택하지 않았습니다.'}</h3></div></div><p>생산 조건의 가정이 바뀌었다고 제품에 순위나 윤리 점수를 매기지 않습니다. 같은 의견을 유지해도 불이익이 없습니다.</p>`}<details class="rr-sources"><summary>핵심 개념 짧게 확인</summary><p>정부 · 공정 경쟁과 시장의 문제에 대응 / 기업 · 사회적 책임과 기업가 정신 / 노동자 · 권리 보장과 협력 / 소비자 · 합리적·윤리적 소비</p><h3>가격이 높으면 항상 더 윤리적인 제품일까요?</h3><div class="rr-perspective-tabs">${button('그렇다','concept','yes',model.conceptAnswer==='yes')}${button('가격만으로 알 수 없다','concept','no',model.conceptAnswer==='no')}</div>${model.conceptAnswer?`<p role="status">${model.conceptAnswer==='no'?'맞습니다.':'다시 살펴보세요.'} 가격만으로 노동·환경 조건을 확인할 수 없습니다. 생산 자료와 검증 근거가 필요합니다.</p>`:''}</details><p class="rr-note">결과를 보관하려면 기기에서 스크린샷을 찍어 주세요. 작성한 내용은 현재 탭에만 남고 새로고침하면 사라집니다. 이름·학번은 적지 마세요.</p></section>`;
}
function render(focus=false){const root=host();root.innerHTML=`<div class="ripple ${model.teacher?'rr-teacher':''}"><div class="rr-top"><button type="button" class="page-return" data-action="goHome">← 전체 콘텐츠</button><label class="teacher-control"><input type="checkbox" data-rr-teacher ${model.teacher?'checked':''}><span class="teacher-label-text">교사 시연 모드</span></label></div><header class="rr-header">${window.GalpiCurriculum.header('ripple')}<h1>선택의 파장</h1><span>티셔츠 한 장에서 시작하는, 지속가능한 시장의 선택.</span></header>${model.teacher?'<p class="rr-teacher-note">교사 시연 · 선택한 뒤 다음 단계로 정보를 공개합니다. 의견에는 정답을 매기지 않습니다.</p>':''}<p class="rr-note"><button type="button" class="btn" data-action="openIntervention">정부의 개입 실험실로 →</button> 가격 담합·공공재·외부 효과를 직접 비교해 보세요.</p><div class="rr-tabs" role="tablist" aria-label="선택의 파장 학습 모드">${[['simulation','선택의 파장'],['cases','세상 속 사례'],['reflection','다시 생각하기']].map(([key,label])=>`<button id="rr-tab-${key}" type="button" role="tab" data-rr="mode" data-value="${key}" aria-controls="rr-body" aria-selected="${model.mode===key}" tabindex="${model.mode===key?0:-1}">${label}</button>`).join('')}</div><div id="rr-body" role="tabpanel" aria-labelledby="rr-tab-${model.mode}" tabindex="-1">${model.mode==='simulation'?simulation():model.mode==='cases'?caseExplore():reflection()}</div></div>`;if(focus)document.querySelector('#rr-body').focus({preventScroll:true});}
function open(){document.body.classList.remove('teacher-mode');setNav('social');location.hash='ripple';render();host().focus({preventScroll:true});window.scrollTo(0,0);}
function nextSim(){if(model.step===0&&!model.product||model.step===1&&model.visited.length<5||model.step===2&&!model.company||model.step===3&&(!model.policy||!model.demand))return;model.step=Math.min(4,model.step+1);model.unlocked=Math.max(model.unlocked,model.step);}
function nextCase(){const cs=caseState();if(cs.stage===1&&cs.initial===null||cs.stage===3&&cs.seen.length<4||cs.stage===4&&(cs.final===null||!cs.criteria.length))return;if(cs.stage===1)cs.revealed=true;cs.stage=Math.min(5,cs.stage+1);if(cs.stage===5)cs.completed=true;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-rr]');if(!b||b.disabled)return;const value=b.dataset.value,cs=caseState(),action=b.dataset.rr;
 switch(action){case 'mode':model.mode=value;break;case 'product':model.product=value;break;case 'pipeline':model.pipeline=Number(value);if(!model.visited.includes(model.pipeline))model.visited.push(model.pipeline);break;case 'company':model.company=value;model.actor=value==='safety'?'노동자':'기업';break;case 'policy':model.policy=value;model.actor='정부';break;case 'demand':model.demand=value;model.actor='소비자';break;case 'actor':model.actor=value;break;case 'stage':if(Number(value)<=model.unlocked)model.step=Number(value);break;case 'sim-prev':model.step=Math.max(0,model.step-1);break;case 'sim-next':nextSim();break;case 'case':model.caseId=value;break;case 'case-initial':cs.initial=Number(value);break;case 'case-final':cs.final=Number(value);break;case 'case-actor':cs.actor=value;if(!cs.seen.includes(value))cs.seen.push(value);break;case 'case-prev':cs.stage=Math.max(0,cs.stage-1);break;case 'case-next':nextCase();break;case 'reflect-sim':model.reflectSource='simulation';model.mode='reflection';break;case 'reflect-case':model.reflectSource=model.caseId;model.mode='reflection';break;case 'reflect-actor':model.reflectActor=value;break;case 'final-product':model.finalProduct=value;break;case 'concept':model.conceptAnswer=value;break;case 'resume-source':if(model.reflectSource==='simulation')model.mode='simulation';else{model.caseId=model.reflectSource;model.mode='cases';}break;}
 const position=window.scrollY;render();const same=[...document.querySelectorAll('[data-rr]')].find(x=>x.dataset.rr===action&&x.dataset.value===value&&!x.disabled);if(['sim-next','sim-prev','case-next','case-prev','stage','mode','reflect-case','reflect-sim','resume-source','case'].includes(action)){document.querySelector('#rr-body').focus({preventScroll:true});document.querySelector('#rr-body').scrollIntoView({behavior:'auto',block:'start'});}else{same?.focus({preventScroll:true});window.scrollTo(0,position);}
 document.querySelector('#statusAnnouncer').textContent=['sim-next','case-next'].includes(action)?'다음 단계의 정보가 공개되었습니다.':'선택이 반영되었습니다.';
});
document.addEventListener('change',e=>{if(e.target.matches('[data-rr-teacher]')){model.teacher=e.target.checked;render();document.querySelector('[data-rr-teacher]').focus({preventScroll:true});}if(e.target.matches('[data-rr-criteria]')){const cs=caseState(),key=e.target.dataset.rrCriteria;cs.criteria=e.target.checked?[...new Set([...cs.criteria,key])]:cs.criteria.filter(x=>x!==key);const active=key;render();[...document.querySelectorAll('[data-rr-criteria]')].find(x=>x.dataset.rrCriteria===active)?.focus({preventScroll:true});}if(e.target.matches('[data-rr-select]')){model.reflectSource=e.target.value;render();document.querySelector('[data-rr-select]').focus({preventScroll:true});}});
document.addEventListener('input',e=>{if(e.target.dataset.rrText==='case')caseState().reason=e.target.value;if(e.target.dataset.rrText==='simulation')model.reason=e.target.value;});
document.addEventListener('keydown',e=>{if(!e.target.matches('.rr-tabs [role=tab]'))return;const tabs=[...document.querySelectorAll('.rr-tabs [role=tab]')],i=tabs.indexOf(e.target);const index=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(index!==null){e.preventDefault();model.mode=tabs[index].dataset.value;render();document.querySelector(`[data-rr=mode][data-value=${model.mode}]`).focus({preventScroll:true});}});
window.GalpiRipple={open,derive,snapshot:()=>JSON.parse(JSON.stringify(model))};
document.addEventListener('DOMContentLoaded',()=>{if(location.hash==='#ripple')open();});
})();
