(()=>{
'use strict';
const E=window.GalpiToolkitEngine,content=document.querySelector('#content'),app=document.querySelector('#app');
const S={tab:'groups',setupOpen:true,class:E.setup(20,'',''),draft:{max:'20',base:'',today:''},groupCount:'5',leaders:true,groups:[],previous:null,revision:0,picks:[],duplicate:false,lastPick:null,orderMode:'groups',orderCount:'5',order:[],done:[],linkedRevision:null,error:'',message:'',pending:null,timer:{duration:600000,remaining:600000,end:0,running:false,finished:false,sound:false},minutes:'10',seconds:'0'};
const h=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,disabled=false,primary=false)=>`<button type="button" class="btn ${primary?'primary':''}" data-tk="${action}" ${disabled?'disabled':''}>${label}</button>`;
const nfield=(id,label,value,min,max)=>`<label class="tk-field" for="${id}"><span>${label}</span><input id="${id}" type="number" min="${min}" max="${max}" step="1" value="${h(value)}" data-tk-field="${id}"></label>`;
function say(message,error=false){S[error?'error':'message']=message;render();document.querySelector('#tk-feedback')?.focus({preventScroll:true});}
function currentTime(){const t=S.timer;return Math.max(0,t.running?t.end-Date.now():t.remaining);}
function format(ms){const seconds=Math.ceil(ms/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function setupPanel(){return `<details class="panel tk-setup" ${S.setupOpen?'open':''}><summary><span class="tk-setup-title">공통 학급 설정</span><span class="tk-count">${S.class.participants.length}명 참여</span></summary><p class="subtle">출석번호만 사용합니다. 새로고침하면 모든 설정과 결과가 초기화됩니다.</p><div class="tk-settings">${nfield('max','최대 출석번호',S.draft.max,1,500)}<label class="tk-field"><span>기본 제외 번호</span><input data-tk-field="base" value="${h(S.draft.base)}" placeholder="예: 7, 19"></label><label class="tk-field"><span>오늘 제외 번호</span><input data-tk-field="today" value="${h(S.draft.today)}" placeholder="예: 3, 12-14"></label></div><p class="subtle">현재 적용: ${S.class.max}번까지 · 기본 제외 ${S.class.basic.join(', ')||'없음'} · 오늘 제외 ${S.class.daily.join(', ')||'없음'}</p><div class="tk-actions">${button('apply','학급 설정 적용',false,true)}</div><fieldset class="tk-exclusions"><legend>번호 버튼으로 제외/해제</legend><label><input type="radio" name="tk-exclude-kind" value="base" checked> 기본 제외</label><label><input type="radio" name="tk-exclude-kind" value="today"> 오늘 제외</label><p class="subtle">번호 선택은 입력란에 반영됩니다. ‘학급 설정 적용’으로 확정하세요. 기본/오늘 중복 제외는 한 번만 계산합니다.</p><div class="tk-numbers">${Array.from({length:S.class.max},(_,i)=>{const n=i+1,b=S.class.basic.includes(n),d=S.class.daily.includes(n);return `<button type="button" data-tk-number="${n}" aria-label="${n}번${b?' 기본 제외':''}${d?' 오늘 제외':''}" aria-pressed="${b||d}" class="${b?'tk-basic':''} ${d?'tk-today':''}">${n}${b?'<small>기본</small>':''}${d?'<small>오늘</small>':''}</button>`;}).join('')}</div></fieldset></details>`;}
function groupPanel(){const empty=!S.class.participants.length;return `<section class="panel"><h2 class="subhead">랜덤 조 나누기</h2><div class="tk-settings">${nfield('groupCount','조 개수',S.groupCount,1,500)}<label class="tk-check"><input type="checkbox" data-tk-field="leaders" ${S.leaders?'checked':''}> 조장 랜덤 선정</label></div><div class="tk-actions">${button('group',S.groups.length?'조 다시 나누기':'조 나누기 시작',empty,true)}${button('leaders','조장만 다시 뽑기',!S.groups.length||!S.leaders)}${button('restore','이전 결과 복원',!S.previous)}${button('copyGroups','결과 복사',!S.groups.length)}${button('linkOrder','발표 순서 정하기',!S.groups.length)}</div><div class="tk-group-grid">${S.groups.map(g=>`<article class="tk-group"><h3>${g.name}<small>${g.members.length}명</small></h3><p>${g.members.map(n=>`<span class="tk-member ${g.leader===n?'tk-leader':''}">${n}번${g.leader===n?' · 조장':''}</span>`).join('')}</p></article>`).join('')}</div></section>`;}
function pickerPanel(){const empty=!S.class.participants.length,available=S.class.participants.filter(n=>!S.picks.includes(n));return `<section class="panel"><h2 class="subhead">랜덤 번호 추첨</h2><label class="tk-check"><input type="checkbox" data-tk-field="duplicate" ${S.duplicate?'checked':''}> 중복 허용 추첨</label><p class="subtle">${S.duplicate?'참여 학생 중 매번 추첨합니다.':'한 회차에 각 학생이 한 번씩 선정됩니다.'}</p><div class="tk-big" aria-live="polite">${S.lastPick===null?'—':S.lastPick+'번'}</div>${!S.duplicate&&!available.length&&!empty?'<p class="tk-complete">추첨 완료! 모든 학생이 선정되었습니다. 기록을 초기화하면 다시 시작할 수 있습니다.</p>':''}<div class="tk-actions">${button('pick',S.lastPick===null?'번호 추첨하기':'다시 추첨하기',empty||(!S.duplicate&&!available.length),true)}${button('clearPicks','추첨 기록 초기화',!S.picks.length)}</div><h3>추첨 기록 (${S.picks.length}회)</h3><p class="tk-record">${S.picks.map((n,i)=>`${i+1}. ${n}번`).join(' → ')||'아직 추첨하지 않았습니다.'}</p></section>`;}
function orderPanel(){const current=S.order[0],next=S.order[1];const stale=S.linkedRevision!==null&&S.linkedRevision!==S.revision;return `<section class="panel"><h2 class="subhead">발표 순서 정하기</h2><div class="tk-settings"><label class="tk-field"><span>발표 대상</span><select data-tk-field="orderMode"><option value="groups" ${S.orderMode==='groups'?'selected':''}>모둠별 발표</option><option value="individual" ${S.orderMode==='individual'?'selected':''}>개인별 발표</option></select></label>${S.orderMode==='groups'&&!S.groups.length?nfield('orderCount','발표할 조 개수',S.orderCount,1,500):''}</div>${S.orderMode==='groups'?`<p class="subtle">${S.groups.length?'현재 조 편성 결과를 사용합니다.':'조 편성 없이 조 이름으로 발표 순서를 만듭니다.'}</p>`:''}${stale?'<div class="tk-warning">조 편성이 변경되었습니다. 기존 발표 진행은 보존되어 있습니다. 새 조를 사용하려면 재연동하세요.</div>':''}<div class="tk-actions">${button('order',S.order.length||S.done.length?'남은 대상만 재추첨':'랜덤 발표 순서 생성',S.orderMode==='individual'&&!S.class.participants.length,false)}${button('relink','현재 조로 재연동',!S.groups.length||S.orderMode!=='groups')}${button('copyOrder','발표 순서 복사',!S.order.length&&!S.done.length)}</div><div class="tk-present"><article><p class="subject-eyebrow">NOW PRESENTING · 현재 발표</p><strong>${current?h(current.name):S.done.length?'모든 발표 완료':'순서를 생성하세요'}</strong>${current?.members?`<p>${current.members.map(n=>n+'번').join(', ')}</p>`:''}</article><article><p class="subject-eyebrow">NEXT · 다음 발표</p><strong>${next?h(next.name):'—'}</strong></article></div>${button('complete','발표 완료 · 다음 대상으로 이동',!S.order.length,true)}<h3>전체 순서 · 남은 ${S.order.length}개</h3><ol class="tk-order">${S.order.map((x,i)=>`<li ${i===0?'aria-current="step"':''}>${h(x.name)} ${i===0?'· 현재':''}</li>`).join('')}</ol><h3>COMPLETED · 발표 완료 (${S.done.length})</h3><p>${S.done.map(x=>h(x.name)).join(' → ')||'아직 완료된 발표가 없습니다.'}</p></section>`;}
function timerPanel(){const t=S.timer;return `<section class="panel tk-timer" id="tk-timer"><h2 class="subhead">수업 타이머</h2><div class="tk-actions">${[1,3,5,10,15].map(n=>button('preset-'+n,n+'분')).join('')}</div><div class="tk-settings tk-time-inputs">${nfield('minutes','분',S.minutes,0,999)}${nfield('seconds','초',S.seconds,0,59)}</div><div class="tk-big" data-tk-clock>${format(currentTime())}</div><progress data-tk-progress max="${t.duration}" value="${currentTime()}" aria-label="남은 시간"></progress><p class="tk-complete" data-tk-finished ${t.finished?'':'hidden'} role="status">활동 시간이 종료되었습니다.</p><div class="tk-actions">${button('start',t.remaining<t.duration?'계속':'시작',t.running||currentTime()<=0,true)}${button('pause','일시정지',!t.running)}${button('resetTimer','초기화')}${button('fullscreen','전체 화면')}</div><label class="tk-check"><input type="checkbox" data-tk-field="sound" ${t.sound?'checked':''}> 종료 알림음 ON</label><p class="subtle">타이머는 다른 도구와 학습 화면에서도 계속 작동합니다. 브라우저가 절전되면 돌아왔을 때 실제 경과 시간을 반영합니다.</p></section>`;}
function render(){if(!content.querySelector('.toolkit'))return;const focus=document.activeElement?.dataset?.tkField;content.innerHTML=`<div class="toolkit"><section class="subject-intro"><div><p class="subject-eyebrow">CLASSROOM TOOLKIT</p><h1>수업 도구</h1><p class="subject-description">수업에 필요한 순간, 간편하게.</p></div></section>${S.pending?`<div class="panel tk-warning" role="alert"><p>${h(S.pending.message)}</p>${button('confirm','확인하고 적용',false,true)}${button('cancel','취소')}</div>`:''}<p id="tk-feedback" class="${S.error?'tk-error':'subtle'}" tabindex="-1" role="status">${h(S.error||S.message)}</p>${setupPanel()}<nav class="tk-tabs" aria-label="수업 도구 선택">${[['groups','랜덤 조 나누기'],['picker','랜덤 번호 추첨'],['order','발표 순서'],['timer','수업 타이머']].map(([key,label])=>`<button type="button" data-tk-tab="${key}" aria-pressed="${S.tab===key}">${label}</button>`).join('')}</nav>${({groups:groupPanel,picker:pickerPanel,order:orderPanel,timer:timerPanel})[S.tab]()}</div>`;if(focus)content.querySelector(`[data-tk-field="${focus}"]`)?.focus({preventScroll:true});updateClock();}
function open(){document.body.classList.remove('teacher-mode');document.querySelectorAll('[data-nav]').forEach(n=>n.classList.toggle('nav-active',n.dataset.nav==='toolkit'));history.replaceState(null,'','#toolkit');content.innerHTML='<div class="toolkit"></div>';render();window.scrollTo(0,0);}
function request(message,fn){S.pending={message,fn};render();}
function invalidateOrder(){S.revision++;}
function applySetup(){const c=E.setup(S.draft.max,S.draft.base,S.draft.today);if(JSON.stringify(c)===JSON.stringify(S.class)){say('현재 설정과 같습니다.');return;}const fn=()=>{S.class=c;S.draft={max:String(c.max),base:c.basic.join(', '),today:c.daily.join(', ')};S.groups=[];S.previous=null;S.picks=[];S.lastPick=null;S.order=[];S.done=[];S.linkedRevision=null;S.revision++;S.message=`학급 설정 적용: ${c.participants.length}명 참여${!c.participants.length?' · 모든 학생이 제외되었습니다.':''}`;};if(S.groups.length||S.picks.length||S.order.length||S.done.length)request('학급 설정을 변경하면 조 편성·추첨 기록·발표 순서가 초기화됩니다. 타이머는 유지됩니다. 적용할까요?',fn);else{fn();render();}}
function saveGroups(next){S.previous=S.groups.length?structuredClone(S.groups):null;S.groups=next;invalidateOrder();S.message='조 편성이 완료되었습니다.';render();}
function newOrder(link=false){const fn=()=>{S.order=E.shuffle(S.orderMode==='individual'?S.class.participants.map(n=>({name:n+'번',number:n})):S.groups.length?structuredClone(S.groups):Array.from({length:E.integer(S.orderCount,1,500,'조 개수')},(_,i)=>({name:(i+1)+'조'})));S.done=[];S.linkedRevision=S.orderMode==='groups'&&S.groups.length?S.revision:null;S.tab='order';render();};if(link&&(S.order.length||S.done.length))request('현재 발표 진행을 초기화하고 새 조 편성으로 다시 연결할까요?',fn);else fn();}
async function copy(text){try{await navigator.clipboard.writeText(text);say('결과를 복사했습니다.');}catch{S.message='자동 복사가 제한되었습니다. 아래 텍스트를 선택해 복사하세요.';render();const area=document.createElement('textarea');area.className='tk-copy';area.value=text;area.setAttribute('aria-label','복사할 결과');content.querySelector('.toolkit').append(area);area.focus();area.select();}}
let audio;
function enableAudio(){try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{S.message='이 브라우저에서는 알림음을 사용할 수 없습니다.';}}
function beep(){if(!S.timer.sound||!audio)return;try{const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=660;gain.gain.setValueAtTime(.1,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.4);osc.start();osc.stop(audio.currentTime+.4);}catch{}}
function setDuration(ms){if(S.timer.running){request('진행 중인 타이머를 중지하고 새 시간을 적용할까요?',()=>duration(ms));return;}duration(ms);}
function duration(ms){Object.assign(S.timer,{duration:ms,remaining:ms,end:0,running:false,finished:false});S.minutes=String(Math.floor(ms/60000));S.seconds=String(ms/1000%60);render();updateClock();}
function action(key){S.error='';S.message='';switch(key){
case 'apply':applySetup();break;
case 'confirm':{const pending=S.pending;S.pending=null;pending.fn();render();break;}
case 'cancel':S.pending=null;render();break;
case 'group':saveGroups(E.groups(S.class.participants,S.groupCount,S.leaders));break;
case 'leaders':saveGroups(S.groups.map(g=>({...g,members:[...g.members],leader:g.members[E.random(g.members.length)]})));break;
case 'restore':{const old=S.groups;S.groups=S.previous;S.previous=old;S.leaders=S.groups.some(g=>g.leader!==null);invalidateOrder();render();break;}
case 'copyGroups':copy(S.groups.map(g=>`${g.name} (${g.members.length}명): ${g.members.map(n=>n+'번').join(', ')}${g.leader?' / 조장 '+g.leader+'번':''}`).join('\n'));break;
case 'linkOrder':S.orderMode='groups';newOrder(true);break;
case 'relink':newOrder(true);break;
case 'order':if(S.order.length||S.done.length){S.order=E.shuffle(S.order);say('완료한 대상은 유지하고 남은 대상만 섞었습니다.');}else newOrder();break;
case 'complete':if(S.order.length)S.done.push(S.order.shift());render();break;
case 'copyOrder':copy(`발표 완료: ${S.done.map(x=>x.name).join(', ')||'없음'}\n남은 순서:\n${S.order.map((x,i)=>`${i+1}. ${x.name}`).join('\n')}`);break;
case 'pick':{const pool=S.duplicate?S.class.participants:S.class.participants.filter(n=>!S.picks.includes(n));if(!pool.length)throw Error('추첨 대상이 없습니다.');S.lastPick=pool[E.random(pool.length)];S.picks.push(S.lastPick);render();break;}
case 'clearPicks':S.picks=[];S.lastPick=null;render();break;
case 'setTimer':setDuration((E.integer(S.minutes,0,999,'분')*60+E.integer(S.seconds,0,59,'초'))*1000||(()=>{throw Error('1초 이상 입력하세요.');})());break;
case 'start':if(!S.timer.running&&S.timer.remaining>0){if(S.timer.sound)enableAudio();S.timer.end=Date.now()+S.timer.remaining;S.timer.running=true;S.timer.finished=false;}render();break;
case 'pause':updateClock();S.timer.remaining=currentTime();S.timer.running=false;render();break;
case 'resetTimer':duration(S.timer.duration);break;
case 'fullscreen':{const target=document.querySelector('#tk-timer');if(document.fullscreenElement)document.exitFullscreen?.();else if(target.requestFullscreen)target.requestFullscreen().catch(()=>say('전체 화면이 제한되어 있습니다. 브라우저 전체 화면 기능을 사용하세요.',true));else say('이 브라우저는 전체 화면 API를 지원하지 않습니다.',true);break;}
default:if(key.startsWith('preset-'))setDuration(Number(key.slice(7))*60000);
}}
app.addEventListener('click',e=>{const tab=e.target.closest('[data-tk-tab]');if(tab){S.tab=tab.dataset.tkTab;S.error='';S.message='';render();document.querySelector(`[data-tk-tab="${S.tab}"]`)?.focus();return;}const number=e.target.closest('[data-tk-number]');if(number){try{const kind=content.querySelector('[name="tk-exclude-kind"]:checked').value,max=E.integer(S.draft.max,1,500,'최대 출석번호'),a=new Set(E.exclusions(S.draft[kind],max)),n=Number(number.dataset.tkNumber);if(n>max)throw Error('최대 출석번호를 적용한 뒤 번호를 선택하세요.');a.has(n)?a.delete(n):a.add(n);S.draft[kind]=[...a].sort((a,b)=>a-b).join(', ');content.querySelector(`[data-tk-field="${kind}"]`).value=S.draft[kind];number.classList.toggle('tk-draft',a.has(n));number.setAttribute('aria-pressed',String(a.has(n)));S.message='번호 선택을 입력란에 반영했습니다. 학급 설정 적용으로 확정하세요.';content.querySelector('#tk-feedback').textContent=S.message;}catch(err){say(err.message,true);}return;}const cmd=e.target.closest('[data-tk]');if(cmd){try{action(cmd.dataset.tk);}catch(err){say(err.message,true);}}});
app.addEventListener('input',e=>{const key=e.target.dataset.tkField;if(!key)return;if(['max','base','today'].includes(key))S.draft[key]=e.target.value;else if(['groupCount','orderCount','minutes','seconds'].includes(key))S[key]=e.target.value;});
app.addEventListener('change',e=>{const key=e.target.dataset.tkField;if(key==='minutes'||key==='seconds'){try{S.error='';const ms=(E.integer(S.minutes,0,999,'분')*60+E.integer(S.seconds,0,59,'초'))*1000;if(!ms)throw Error('1초 이상 입력하세요.');if(ms!==S.timer.duration)setDuration(ms);}catch(err){say(err.message,true);}return;}if(key==='leaders'){S.leaders=e.target.checked;if(S.groups.length){S.previous=structuredClone(S.groups);S.groups=S.groups.map(g=>({...g,leader:S.leaders?g.members[E.random(g.members.length)]:null}));invalidateOrder();}render();}if(key==='sound'){S.timer.sound=e.target.checked;if(S.timer.sound)enableAudio();render();}if(key==='duplicate'){S.duplicate=e.target.checked;render();}if(key==='orderMode'&&e.target.value!==S.orderMode){const mode=e.target.value;if(S.order.length||S.done.length)request('발표 대상을 변경하면 현재 발표 진행이 초기화됩니다. 변경할까요?',()=>{S.orderMode=mode;S.order=[];S.done=[];S.linkedRevision=null;});else{S.orderMode=mode;render();}}});
content.addEventListener('toggle',e=>{if(e.target.matches('.tk-setup'))S.setupOpen=e.target.open;},true);
const dock=document.createElement('aside');dock.className='tk-timer-dock';dock.hidden=true;dock.setAttribute('aria-label','진행 중인 수업 타이머');dock.innerHTML='<button type="button">수업 타이머 <strong data-tk-dock-clock></strong><span data-tk-dock-status></span></button>';document.body.append(dock);dock.querySelector('button').addEventListener('click',()=>{S.tab='timer';open();});
function updateClock(){const t=S.timer,ms=currentTime();if(t.running&&ms<=0){t.running=false;t.remaining=0;t.finished=true;beep();if(content.querySelector('.toolkit'))render();}document.querySelectorAll('[data-tk-clock],[data-tk-dock-clock]').forEach(el=>el.textContent=format(currentTime()));document.querySelectorAll('[data-tk-progress]').forEach(el=>el.value=currentTime());document.querySelectorAll('[data-tk-finished]').forEach(el=>el.hidden=!t.finished);dock.hidden=!(t.running||t.finished||t.remaining<t.duration);dock.querySelector('[data-tk-dock-status]').textContent=t.finished?' · 종료':!t.running?' · 일시정지':'';}
setInterval(updateClock,200);document.addEventListener('visibilitychange',updateClock);
window.GalpiToolkit=Object.freeze({open});if(location.hash==='#toolkit')open();
})();
